# This definition was generated by the protobuf utility graphql transform. DO NOT EDIT!
# Source proto: ComplexMessage
from n4_gql import N4
from common_gql import common  # TODO: this import is invalid
import strawberry
from enum import Enum


# TODO: Use module to protect types rather than nest them. Helps with type hintss 


@strawberry.type
class ComplexMessage:
	@strawberry.type
	class N5:
		@strawberry.enum
		class N5Types(Enum):
			DEFAULT = 0
			type1 = 1
			type2 = 2
			type3 = 3

		types: N5.N5Types  # Invalid Type Definition
		data: str

	@strawberry.type
	class RawMsgsByIdEntry:
		key: str
		value: common.RawMsg  # This will be invalid after import fix

	@strawberry.type
	class N4sByIdEntry:
		key: str
		value: N4

	@strawberry.type
	class N5sByIdEntry:
		key: str
		value: N5  # Type not detected sad.

	raw_msgs_by_id: RawMsgsByIdEntry
	n4s: N4
	n4s_by_id: N4sByIdEntry
	n5s_by_id: N5sByIdEntry
