# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomplex.proto\x1a\x0c\x63ommon.proto\"\xaa\x01\n\x02N4\x12\n\n\x02id\x18\x01 \x01(\r\x12 \n\x08raw_msgs\x18\x04 \x03(\x0b\x32\x0e.common.RawMsg\x12,\n\x0eraw_msgs_by_id\x18\x05 \x03(\x0b\x32\x14.N4.RawMsgsByIdEntry\x1a\x42\n\x10RawMsgsByIdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.common.RawMsg:\x02\x38\x01J\x04\x08\x02\x10\x04\"\xff\x03\n\x0e\x43omplexMessage\x12\x38\n\x0eraw_msgs_by_id\x18\x01 \x03(\x0b\x32 .ComplexMessage.RawMsgsByIdEntry\x12\x10\n\x03n4s\x18\x03 \x03(\x0b\x32\x03.N4\x12/\n\tn4s_by_id\x18\x05 \x03(\x0b\x32\x1c.ComplexMessage.N4sByIdEntry\x12/\n\tn5s_by_id\x18\x06 \x03(\x0b\x32\x1c.ComplexMessage.N5sByIdEntry\x1av\n\x02N5\x12)\n\x05types\x18\x01 \x03(\x0e\x32\x1a.ComplexMessage.N5.N5Types\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"7\n\x07N5Types\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05type1\x10\x01\x12\t\n\x05type2\x10\x02\x12\t\n\x05type3\x10\x03\x1a\x42\n\x10RawMsgsByIdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.common.RawMsg:\x02\x38\x01\x1a\x33\n\x0cN4sByIdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\x05value\x18\x02 \x01(\x0b\x32\x03.N4:\x02\x38\x01\x1a\x42\n\x0cN5sByIdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.ComplexMessage.N5:\x02\x38\x01J\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05\"\'\n\x02N6\x12!\n\x05n5val\x18\x01 \x01(\x0b\x32\x12.ComplexMessage.N5b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complex_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _N4_RAWMSGSBYIDENTRY._options = None
  _N4_RAWMSGSBYIDENTRY._serialized_options = b'8\001'
  _COMPLEXMESSAGE_RAWMSGSBYIDENTRY._options = None
  _COMPLEXMESSAGE_RAWMSGSBYIDENTRY._serialized_options = b'8\001'
  _COMPLEXMESSAGE_N4SBYIDENTRY._options = None
  _COMPLEXMESSAGE_N4SBYIDENTRY._serialized_options = b'8\001'
  _COMPLEXMESSAGE_N5SBYIDENTRY._options = None
  _COMPLEXMESSAGE_N5SBYIDENTRY._serialized_options = b'8\001'
  _N4._serialized_start=32
  _N4._serialized_end=202
  _N4_RAWMSGSBYIDENTRY._serialized_start=130
  _N4_RAWMSGSBYIDENTRY._serialized_end=196
  _COMPLEXMESSAGE._serialized_start=205
  _COMPLEXMESSAGE._serialized_end=716
  _COMPLEXMESSAGE_N5._serialized_start=397
  _COMPLEXMESSAGE_N5._serialized_end=515
  _COMPLEXMESSAGE_N5_N5TYPES._serialized_start=460
  _COMPLEXMESSAGE_N5_N5TYPES._serialized_end=515
  _COMPLEXMESSAGE_RAWMSGSBYIDENTRY._serialized_start=130
  _COMPLEXMESSAGE_RAWMSGSBYIDENTRY._serialized_end=196
  _COMPLEXMESSAGE_N4SBYIDENTRY._serialized_start=585
  _COMPLEXMESSAGE_N4SBYIDENTRY._serialized_end=636
  _COMPLEXMESSAGE_N5SBYIDENTRY._serialized_start=638
  _COMPLEXMESSAGE_N5SBYIDENTRY._serialized_end=704
  _N6._serialized_start=718
  _N6._serialized_end=757
# @@protoc_insertion_point(module_scope)
