# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: specials.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0especials.proto\"\xd7\x01\n\x0cTestSpecials\x12\r\n\x05list1\x18\x03 \x03(\t\x12%\n\x04map1\x18\x04 \x03(\x0b\x32\x17.TestSpecials.Map1Entry\x12\x10\n\x06\x66\x61ult1\x18\t \x01(\x08H\x00\x12\x10\n\x06\x66\x61ult2\x18\n \x01(\x08H\x00\x1a+\n\tMap1Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0c\n\ntest_oneofJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x05\x10\tJ\x08\x08(\x10\x80\x80\x80\x80\x02R\nold_field1R\nold_field2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'specials_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTSPECIALS_MAP1ENTRY._options = None
  _TESTSPECIALS_MAP1ENTRY._serialized_options = b'8\001'
  _TESTSPECIALS._serialized_start=19
  _TESTSPECIALS._serialized_end=234
  _TESTSPECIALS_MAP1ENTRY._serialized_start=125
  _TESTSPECIALS_MAP1ENTRY._serialized_end=168
# @@protoc_insertion_point(module_scope)
