# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnested.proto\"\x12\n\x02N2\x12\x0c\n\x04val2\x18\x01 \x01(\t\"Q\n\nTestNested\x12\x1c\n\x04val1\x18\x01 \x01(\x0b\x32\x0e.TestNested.N1\x12\x11\n\x04val2\x18\x02 \x01(\x0b\x32\x03.N2\x1a\x12\n\x02N1\x12\x0c\n\x04val1\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nested_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _N2._serialized_start=16
  _N2._serialized_end=34
  _TESTNESTED._serialized_start=36
  _TESTNESTED._serialized_end=117
  _TESTNESTED_N1._serialized_start=99
  _TESTNESTED_N1._serialized_end=117
# @@protoc_insertion_point(module_scope)
