# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\" \n\x02N3\x12\x0c\n\x04val1\x18\x01 \x01(\r\x12\x0c\n\x04val2\x18\x02 \x01(\r\"\xfb\x02\n\tTestTypes\x12\x0c\n\x04val1\x18\x01 \x01(\x01\x12\x0c\n\x04val2\x18\x02 \x01(\x02\x12\x0c\n\x04val3\x18\x03 \x01(\x05\x12\x0c\n\x04val4\x18\x04 \x01(\x03\x12\x0c\n\x04val5\x18\x05 \x01(\r\x12\x0c\n\x04val6\x18\x06 \x01(\x04\x12\x0c\n\x04val7\x18\x07 \x01(\x11\x12\x0c\n\x04val8\x18\x08 \x01(\x12\x12\x0c\n\x04val9\x18\t \x01(\x07\x12\r\n\x05val10\x18\n \x01(\x06\x12\r\n\x05val11\x18\x0b \x01(\x0f\x12\r\n\x05val12\x18\x0c \x01(\x10\x12\r\n\x05val13\x18\r \x01(\x08\x12\r\n\x05val14\x18\x0e \x01(\t\x12\r\n\x05val15\x18\x0f \x01(\x0c\x12\x15\n\x05val16\x18\x10 \x01(\x0e\x32\x06.TYPES\x12\x12\n\x05val17\x18\x11 \x01(\x0b\x32\x03.N3\x12$\n\x05val18\x18\x12 \x03(\x0b\x32\x15.TestTypes.Val18Entry\x12\x12\n\x05val19\x18\x13 \x03(\x0b\x32\x03.N3\x1a\x31\n\nVal18Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\x05value\x18\x02 \x01(\x0b\x32\x03.N3:\x02\x38\x01**\n\x05TYPES\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05type1\x10\x01\x12\t\n\x05type2\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTTYPES_VAL18ENTRY._options = None
  _TESTTYPES_VAL18ENTRY._serialized_options = b'8\001'
  _TYPES._serialized_start=431
  _TYPES._serialized_end=473
  _N3._serialized_start=15
  _N3._serialized_end=47
  _TESTTYPES._serialized_start=50
  _TESTTYPES._serialized_end=429
  _TESTTYPES_VAL18ENTRY._serialized_start=380
  _TESTTYPES_VAL18ENTRY._serialized_end=429
# @@protoc_insertion_point(module_scope)
